import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Container from "@/components/Container";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "@/providers/SessionProvider";
import { getUser } from "./lib/lucia";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const value = await getUser();
  console.log("Value", value);

  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-zinc-100 text-zinc-900 min-h-screen`}
      >
        <SessionProvider value={value}>
          <Container>
            <Header />
            {children}
            <Footer />
          </Container>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
